
const dataStore = {
  clues: [
    {
      id: 1,
      title: 'Start',
      riddle: 'Go by foot to the library, "quote from a well known book"',
      hint: 'book# - page# - line#',
      answer: '1234',
      image: '',
      video: '',
      type: 'info',
    },
    {
      id: 2,
      title: 'Road Block - Who can feel the rythm?',
      riddle: 'You need to perform this traditional South African mine workers dance. - The gumboot dance.',
      hint: '',
      answer: 'dance monkey',
      video: 'https://www.youtube.com/embed/uuSuKKFzaho',
      image: '',
      type: 'roadblock',
    },
    {
      id: 3,
      title: 'detour - Its Time to Farm',
      riddle: 'You must make your way by foot the outdoor gym. There you will find the water containers required by a local farmer. Take your water container and find the 4 filling stations to fill your container before returning to the farmer. Finally stack the water containers on top of each other to access you next clue.',
      hint: '',
      answer: 'Farmer Carry',
      video: '',
      image: '',
      type: 'detour',
    },
    {
      id: 4,
      title: 'Road Block - Who can copy?',
      riddle: 'Look at the picture below then go to the drawing station to create your own version of the image. You may only return once to view the picture. You have 5 minutes to complete the challenge. If you fail you will have to complete 30 seconds of skipping without stopping or tripping over the skipping rope.',
      hint: 'draw picture',
      answer: '',
      video: '',
      image: 'zulu-wall-painting.jpg',
      type: 'roadblock',
    },
    {
      id: 5,
      title: 'Detour - Can you build it?',
      riddle: 'Build a tower out of plasic cups in under 30 seconds that is at least 60cm high.',
      hint: 'draw picture',
      answer: '',
      video: '',
      image: '',
      type: 'detour',
    },
    {
      id: 6,
      title: 'Detour - a task both team members must complete',
      riddle: 'Make your way to the pool of destiny. You must work together to cross from the square to the triangle. There is no going around!',
      hint: '',
      answer: '',
      video: '',
      image: '../assets/change-we-can-relieve-in-1.png',
      type: 'detour',
    },
    {
      id: 7,
      title: 'Home Run',
      riddle: 'Make your way to the pitstop and final stop of the race. Mountian of headcracking pullups.',
      hint: '',
      answer: '',
      video: '',
      image: '',
      type: 'info',
    },
  ],
};

export default dataStore;
